



[paths]
# Folder for runtime program files.
workDirectory = 'C:\Crap\Coding\Python\NBA2k13\SaveData'
# Path to NBA 2k13 game install directory
gameInstall = 'C:\Program Files (x86)\Steam\steamapps\common\NBA2K13'

# Count of backups to keep for all backed up files.
backupCount = 10


[rarities]
commonChance = 0.45             # Common player chance
rareChance = 0.33               # Rare player chance
epicChance = 0.15               # Epic player chance
legendaryChance = 0.06          # Legendary player chance
godlikeChance = 10.01            # Godlike player chance

# Likelihood of a generated artifact being archetype specific
archetypeBasedArtifactChance = 0.60

[loading]
# All rosters listed here will be automatically scraped
# for CAP data EACH TIME incoming changes are saved.
CAPRosters = ["Premier","Gauntlet"]