import sqlite3
#import lxml.etree as ET
import BaseFunctions as b
import shutil
import DataStorage
import os
import Helpers as h
import Factions

# This file is specifically for functions that are NEVER called automatically during program execution.
# These functions can be hand chosen to perform certain maintenance/debugging operations on the code or
# data.


# This function generates a new, empty Players table in the given dbPath.
def genBlankPlayersTable(dbPath,tableName="Players"):

    playersXMLList = {      "Last_Name": "Text",
                            "First_Name": "Text",
                            "NickName": "Text",
                            "Archetype": "Text",
                            "Rarity": "Text",
                            "CAP_Nick": "Integer",
                            "PMods" : "Text",
                            "Hand": "Integer",
                            "Height": "Integer",
                            "Weight": "Real",
                            "PortrID": "Integer",
                            "GenericF": "Integer",
                            "CF_ID": "Integer",
                            "AudioID_M": "Integer",
                            "NmOrder": "Integer",
                            "SkinTone": "Integer",
                            "Muscles": "Integer",
                            "EyeColor": "Integer",
                            "Bodytype": "Integer",
                            "Clothes": "Integer",
                            "Number": "Integer",
                            "Pos": "Integer",
                            "SecondPos": "Integer",
                            "PlayInitor": "Integer",
                            "PlayStyle": "Integer",
                            "PlayType1": "Integer",
                            "PlayType2": "Integer",
                            "PlayType3": "Integer",
                            "PlayType4": "Integer",
                            "SShtIns": "Integer",
                            "SShtCls": "Integer",
                            "SShtMed": "Integer",
                            "SSht3PT": "Integer",
                            "SShtFT": "Integer",
                            "SLayUp": "Integer",
                            "SDunk": "Integer",
                            "SStdDunk": "Integer",
                            "SShtInT": "Integer",
                            "SPstFdaway": "Integer",
                            "SPstHook": "Integer",
                            "SShtOfD": "Integer",
                            "SBallHndl": "Integer",
                            "SOffHDrib": "Integer",
                            "SBallSec": "Integer",
                            "SPass": "Integer",
                            "SBlock": "Integer",
                            "SSteal": "Integer",
                            "SHands": "Integer",
                            "SOnBallD": "Integer",
                            "SOReb": "Integer",
                            "SDReb": "Integer",
                            "SOLowPost": "Integer",
                            "SDLowPost": "Integer",
                            "SOAwar": "Integer",
                            "SDAwar": "Integer",
                            "SConsis": "Integer",
                            "SStamina": "Integer",
                            "SSpeed": "Integer",
                            "SQuick": "Integer",
                            "SStrength": "Integer",
                            "SVertical": "Integer",
                            "SHustle": "Integer",
                            "SDurab": "Integer",
                            "SPOT": "Integer",
                            "SEmotion": "Integer",
                            "SigSkill1": "Integer",
                            "SigSkill2": "Integer",
                            "SigSkill3": "Integer",
                            "SigSkill4": "Integer",
                            "SigSkill5": "Integer",
                            "TShtTend": "Integer",
                            "TInsShots": "Integer",
                            "TCloseSht": "Integer",
                            "TMidShots": "Integer",
                            "T3PTShots": "Integer",
                            "TPutbacks": "Integer",
                            "TDriveLn": "Integer",
                            "TPullUp": "Integer",
                            "TPumpFake": "Integer",
                            "TTrplThrt": "Integer",
                            "TTTShot": "Integer",
                            "TNoTT": "Integer",
                            "TStrghtDr": "Integer",
                            "TSizeUp": "Integer",
                            "THesitat": "Integer",
                            "TDriveRvL": "Integer",
                            "TCrossov": "Integer",
                            "TSpin": "Integer",
                            "TStepBack": "Integer",
                            "THalfSpin": "Integer",
                            "TDblCross": "Integer",
                            "TBhndBack": "Integer",
                            "THesCross": "Integer",
                            "TInAndOut": "Integer",
                            "TDPSimpDr": "Integer",
                            "TAttackB": "Integer",
                            "TPassOut": "Integer",
                            "THopStep": "Integer",
                            "TSpinLUp": "Integer",
                            "TEuroStep": "Integer",
                            "TRunner": "Integer",
                            "TFadeaway": "Integer",
                            "TStpbJmpr": "Integer",
                            "TSpinJmpr": "Integer",
                            "TDunkvLU": "Integer",
                            "TAlleyOop": "Integer",
                            "TUseGlass": "Integer",
                            "TDrawFoul": "Integer",
                            "TStpThrgh": "Integer",
                            "TVShCrash": "Integer",
                            "TUsePick": "Integer",
                            "TSetPick": "Integer",
                            "TIsolat": "Integer",
                            "TUseOBScr": "Integer",
                            "TSetOBScr": "Integer",
                            "TSpotUp": "Integer",
                            "TPostUp": "Integer",
                            "TGiveGo": "Integer",
                            "TTouches": "Integer",
                            "TPostSpn": "Integer",
                            "TPostDrv": "Integer",
                            "TPostAgBd": "Integer",
                            "TLeavePost": "Integer",
                            "TPostDrpSt": "Integer",
                            "TPostFaceU": "Integer",
                            "TPostBDown": "Integer",
                            "TPostShots": "Integer",
                            "TPostHook": "Integer",
                            "TPostFdawy": "Integer",
                            "TPostShmSh": "Integer",
                            "TPostHopSh": "Integer",
                            "TFlshPass": "Integer",
                            "TThrowAO": "Integer",
                            "THardFoul": "Integer",
                            "TTakeChrg": "Integer",
                            "TPassLane": "Integer",
                            "TOnBalStl": "Integer",
                            "TContShot": "Integer",
                            "TCommFoul": "Integer",
                            "HIso3PLft": "Integer",
                            "HIso3PCtr": "Integer",
                            "HIso3PRgt": "Integer",
                            "HIsoHPLft": "Integer",
                            "HIsoHPCtr": "Integer",
                            "HIsoHPRgt": "Integer",
                            "HP_rLCrnr": "Integer",
                            "HP_rLWing": "Integer",
                            "HP_rTopOA": "Integer",
                            "HP_rRWing": "Integer",
                            "HP_rRCrnr": "Integer",
                            "HSpt3PLCr": "Integer",
                            "HSpt3PLWg": "Integer",
                            "HSpt3PTop": "Integer",
                            "HSpt3PRWg": "Integer",
                            "HSpt3PRCr": "Integer",
                            "HSptMdLBl": "Integer",
                            "HSptMdLWg": "Integer",
                            "HSptMdCtr": "Integer",
                            "HSptMdRWg": "Integer",
                            "HSptMdRBl": "Integer",
                            "HPstRHigh": "Integer",
                            "HPstRLow": "Integer",
                            "HPstLHigh": "Integer",
                            "HPstLLow": "Integer",
                            "HZ1": "Integer",
                            "HZ2": "Integer",
                            "HZ3": "Integer",
                            "HZ4": "Integer",
                            "HZ5": "Integer",
                            "HZ6": "Integer",
                            "HZ7": "Integer",
                            "HZ8": "Integer",
                            "HZ9": "Integer",
                            "HZ10": "Integer",
                            "HZ11": "Integer",
                            "HZ12": "Integer",
                            "HZ13": "Integer",
                            "HZ14": "Integer",
                            "AShtForm": "Integer",
                            "AShtBase": "Integer",
                            "AFadeaway": "Integer",
                            "AContestd": "Integer",
                            "AEscDrPlU": "Integer",
                            "ARunner": "Integer",
                            "AFreeT": "Integer",
                            "ADrPullUp": "Integer",
                            "ASpinJmpr": "Integer",
                            "AHopJmpr": "Integer",
                            "APstFade": "Integer",
                            "APstHook": "Integer",
                            "APstHopSh": "Integer",
                            "APstShmSh": "Integer",
                            "APstDrvStB": "Integer",
                            "APstSpnStB": "Integer",
                            "APstPrtct": "Integer",
                            "APstPrtSpn": "Integer",
                            "AIsoCross": "Integer",
                            "AIsoBhBck": "Integer",
                            "AIsoSpin": "Integer",
                            "AIsoHesit": "Integer",
                            "ALayUp": "Integer",
                            "AGoToDunk": "Integer",
                            "ADunk2": "Integer",
                            "ADunk3": "Integer",
                            "ADunk4": "Integer",
                            "ADunk5": "Integer",
                            "ADunk6": "Integer",
                            "ADunk7": "Integer",
                            "ADunk8": "Integer",
                            "ADunk9": "Integer",
                            "ADunk10": "Integer",
                            "ADunk11": "Integer",
                            "ADunk12": "Integer",
                            "ADunk13": "Integer",
                            "ADunk14": "Integer",
                            "ADunk15": "Integer",
                            "AIntHLght": "Integer",
                            "AIntPreG1": "Integer",
                            "AIntPreG2": "Integer",
                            "AIntPreT1": "Integer",
                            "AIntPreT2": "Integer",
                            "GHeadband": "Integer",
                            "GHdbndLg": "Integer",
                            "GUndrshrt": "Integer",
                            "GUndrsCol": "Integer",
                            "GLeftArm": "Integer",
                            "GLArmCol": "Integer",
                            "GLeftElb": "Integer",
                            "GLElbCol": "Integer",
                            "GLeftWrst": "Integer",
                            "GLWrstC1": "Integer",
                            "GLWrstC2": "Integer",
                            "GLeftFngr": "Integer",
                            "GLFngrCol": "Integer",
                            "GRghtArm": "Integer",
                            "GRArmCol": "Integer",
                            "GRghtElb": "Integer",
                            "GRElbCol": "Integer",
                            "GRghtWrst": "Integer",
                            "GRWrstC1": "Integer",
                            "GRWrstC2": "Integer",
                            "GRghtFngr": "Integer",
                            "GRFngrCol": "Integer",
                            "GPresShrt": "Integer",
                            "GPrsShCol": "Integer",
                            "GLeftLeg": "Integer",
                            "GLLegCol": "Integer",
                            "GLeftKnee": "Integer",
                            "GLKneeCol": "Integer",
                            "GLeftAnkl": "Integer",
                            "GLAnklCol": "Integer",
                            "GRghtLeg": "Integer",
                            "GRLegCol": "Integer",
                            "GRghtKnee": "Integer",
                            "GRKneeCol": "Integer",
                            "GRghtAnkl": "Integer",
                            "GRAnklCol": "Integer",
                            "GSockLngh": "Integer",
                            "GShsBrLck": "Integer",
                            "GShsBrand": "Integer",
                            "GShsModel": "Integer",
                            "GShsUCusC": "Integer",
                            "GShsTHC1": "Integer",
                            "GShsTHC2": "Integer",
                            "GShsTAC1": "Integer",
                            "GShsTAC2": "Integer",
                            "GShsHCol1": "Blob",
                            "GShsHCol2": "Blob",
                            "GShsHCol3": "Blob",
                            "GShsACol1": "Blob",
                            "GShsACol2": "Blob",
                            "GShsACol3": "Blob",
                            "CAP_FaceT": "Integer",
                            "CAP_Hstl": "Integer",
                            "CAP_Hcol": "Integer",
                            "CAP_Hlen": "Integer",
                            "CAP_BStyle": "Integer",
                            "CAP_Moust": "Integer",
                            "CAP_Goatee": "Integer",
                            "CAP_Fhcol": "Integer",
                            "CAP_Eyebr": "Integer",
                            "CAP_T_LftN": "Integer",
                            "CAP_T_LftS": "Integer",
                            "CAP_T_RgtS": "Integer",
                            "CAP_T_LftB": "Integer",
                            "CAP_T_RgtB": "Integer",
                            "CAP_T_LftF": "Integer",
                            "CAP_T_RgtF": "Integer",
                            "HParam1": "Integer",
                            "HParam2": "Integer",
                            "HdBrwHght": "Integer",
                            "HdBrwWdth": "Integer",
                            "HdBrwSlpd": "Integer",
                            "HdNkThck": "Integer",
                            "HdNkFat": "Integer",
                            "HdChnLen": "Integer",
                            "HdChnWdth": "Integer",
                            "HdChnProt": "Integer",
                            "HdJawSqr": "Integer",
                            "HdJawWdth": "Integer",
                            "HdChkHght": "Integer",
                            "HdChkWdth": "Integer",
                            "HdChkFull": "Integer",
                            "HdDefinit": "Integer",
                            "MtULCurve": "Integer",
                            "MtULThick": "Integer",
                            "MtULProtr": "Integer",
                            "MtLLCurve": "Integer",
                            "MtLLThick": "Integer",
                            "MtLLProtr": "Integer",
                            "MtSzHght": "Integer",
                            "MtSzWdth": "Integer",
                            "MtCrvCorn": "Integer",
                            "ErHeight": "Integer",
                            "ErWidth": "Integer",
                            "ErEarLobe": "Integer",
                            "ErTilt": "Integer",
                            "NsNsHght": "Integer",
                            "NsNsWdth": "Integer",
                            "NsNsProtr": "Integer",
                            "NsBnBridge": "Integer",
                            "NsBnDefin": "Integer",
                            "NsBnWdth": "Integer",
                            "NsTipHght": "Integer",
                            "NsTipWdth": "Integer",
                            "NsTipTip": "Integer",
                            "NsTipBnd": "Integer",
                            "NsNtHght": "Integer",
                            "NsNtWdth": "Integer",
                            "EsFrmOpen": "Integer",
                            "EsFrmSpac": "Integer",
                            "EsFrmLwEl": "Integer",
                            "EsFrmUpEl": "Integer",
                            "EsPlcHght": "Integer",
                            "EsPlcWdth": "Integer",
                            "EsPlcRot": "Integer",
                            "EsPlcProt": "Integer",
                            "EsShpOtEl": "Integer",
                            "EsShpInEl": "Integer",
                            "HS_ID": "Integer",
                            "IsRegNBA": "Integer",
                            "IsSpecial": "Integer",
                            "SlotType": "Integer",
                            "IsGener": "Integer",
                            "IsDraftee": "Integer",
                            "IsDrafted": "Integer",
                            "ASA_ID": "Integer",
                            "IsFA": "Integer",
                            "TeamID1": "Integer",
                            "TeamID2": "Integer",
                            "BirthDay": "Integer",
                            "BirthMonth": "Integer",
                            "BirthYear": "Integer",
                            "YearsPro": "Integer",
                            "CollegeID": "Integer",
                            "DraftedBy": "Integer",
                            "DraftYear": "Integer",
                            "DraftRound": "Integer",
                            "DraftPos": "Integer",
                            "Personality": "Integer",
                            "Play4Winner": "Integer",
                            "FinSecurity": "Integer",
                            "Loyalty": "Integer",
                            "PeakAgeS": "Integer",
                            "PeakAgeE": "Integer",
                            "MinsAsg": "Integer",
                            "Morale": "Integer",
                            "Fatigue": "Integer",
                            "FARestr": "Integer",
                            "CtrThoughts": "Integer",
                            "InjDaysLeft": "Integer",
                            "InjType": "Integer",
                            "StatY0": "Integer",
                            "StatY1": "Integer",
                            "StatY2": "Integer",
                            "StatY3": "Integer",
                            "StatY4": "Integer",
                            "StatY5": "Integer",
                            "StatY6": "Integer",
                            "StatY7": "Integer",
                            "StatY8": "Integer",
                            "StatY9": "Integer",
                            "StatY10": "Integer",
                            "StatY11": "Integer",
                            "StatY12": "Integer",
                            "StatY13": "Integer",
                            "StatY14": "Integer",
                            "StatY15": "Integer",
                            "StatY16": "Integer",
                            "StatY17": "Integer",
                            "StatY18": "Integer",
                            "StatY19": "Integer",
                            "StatPOs": "Integer",
                            "GH_CarPts": "Integer",
                            "GH_CarFGM": "Integer",
                            "GH_CarFGA": "Integer",
                            "GH_CarStl": "Integer",
                            "GH_CarBlk": "Integer",
                            "GH_Car3PM": "Integer",
                            "GH_Car3PA": "Integer",
                            "GH_CarFTM": "Integer",
                            "GH_CarFTA": "Integer",
                            "GH_CarOReb": "Integer",
                            "GH_CarDReb": "Integer",
                            "GH_CarRebs": "Integer",
                            "GH_CarAst": "Integer",
                            "GH_SeaPts": "Integer",
                            "GH_SeaFGM": "Integer",
                            "GH_SeaFGA": "Integer",
                            "GH_SeaStl": "Integer",
                            "GH_SeaBlk": "Integer",
                            "GH_Sea3PM": "Integer",
                            "GH_Sea3PA": "Integer",
                            "GH_SeaFTM": "Integer",
                            "GH_SeaFTA": "Integer",
                            "GH_SeaOReb": "Integer",
                            "GH_SeaDReb": "Integer",
                            "GH_SeaRebs": "Integer",
                            "GH_SeaAst": "Integer",
                            "BirdYears": "Integer",
                            "CClrYears": "Integer",
                            "CRole": "Integer",
                            "COption": "Integer",
                            "CNoTrade": "Integer",
                            "CYear1": "Integer",
                            "CYear2": "Integer",
                            "CYear3": "Integer",
                            "CYear4": "Integer",
                            "CYear5": "Integer",
                            "CYear6": "Integer",
                            "SgndTYWith": "Integer",
                            "YrsForCurT": "Integer",
                            "ExtraValue1": "Text",
                            "ExtraValue2": "Text",
                            "ExtraValue3": "Text",
                            "ExtraValue4": "Text",
                            "ExtraValue5": "Text",
                            "ExtraValue6": "Text",
                            "ExtraValue7": "Text",
                            "ExtraValue8": "Text",
                            "ExtraValue9": "Text",
                            "ExtraValue10": "Text",
                            "ExtraValue11": "Text",
                            "ExtraValue12": "Text",
                            "ExtraValue13": "Text",
                            "ExtraValue14": "Text",
                            "ExtraValue15": "Text",
                            "ExtraValue16": "Text",
                            "ExtraValue17": "Text",
                            "ExtraValue18": "Text",
                            "ExtraValue19": "Text",
                            "ExtraValue20": "Text",
                            "ExtraValue21": "Text",
                            "ExtraValue22": "Text",
                            "ExtraValue23": "Text",
                            "ExtraValue24": "Text",
                            "ExtraValue25": "Text",
                            "ExtraValue26": "Text",
                            "ExtraValue27": "Text",
                            "ExtraValue28": "Text",
                            "ExtraValue29": "Text",
                            "ExtraValue30": "Text",
                            "ExtraValue31": "Text",
                            "ExtraValue32": "Text",
                            "ExtraValue33": "Text",
                            "ExtraValue34": "Text",
                            "ExtraValue35": "Text",
                            "ExtraValue36": "Text",
                            "ExtraValue37": "Text",
                            "ExtraValue38": "Text",
                            "ExtraValue39": "Text",
                            "ExtraValue40": "Text",
                            "ExtraValue41": "Text",
                            "ExtraValue42": "Text",
                            "ExtraValue43": "Text",
                            "ExtraValue44": "Text",
                            "ExtraValue45": "Text",
                            "ExtraValue46": "Text",
                            "ExtraValue47": "Text",
                            "ExtraValue48": "Text",
                            "ExtraValue49": "Text",
                            "ExtraValue50": "Text"}
    conn = sqlite3.connect(dbPath)


    cursor = conn.cursor()

    cursor.execute("CREATE TABLE '" + tableName + "' ('SpriteID' INTEGER NOT NULL UNIQUE, PRIMARY KEY('SpriteID'));")
    for key in playersXMLList.keys():
        if(playersXMLList[key] in ["Text","Blob"]):
            defaultVal = "NULL"
        else:
            defaultVal = "0"
        cursor.execute(f"ALTER TABLE {tableName} ADD COLUMN {key} {playersXMLList[key].upper()} DEFAULT {defaultVal}")

    # Commit the changes
    conn.commit()
# This function adds all Player elements in a given Players.xml file to the
# given SQLite database by dbPath.
def convertPlayersXMLToSQL(xmlPath,dbPath,tableName="Players"):
    tree = ET.parse(xmlPath)
    root = tree.getroot()

    conn = sqlite3.connect(dbPath)
    cursor = conn.cursor()

    def getPlayerDictTemplate():
        PLAYER_DICT_TEMPLATE = {"Last_Name": None,
                                "First_Name": None,
                                "NickName": None,
                                "Archetype": None,
                                "Rarity": None,
                                "CAP_Nick": None,
                                "ArtifactName": None,
                                "ArtifactDesc": None,
                                "ArtifactCode": None,
                                "Hand": None,
                                "Height": None,
                                "Weight": None,
                                "PortrID": None,
                                "GenericF": None,
                                "CF_ID": None,
                                "AudioID_M": None,
                                "NmOrder": None,
                                "SkinTone": None,
                                "Muscles": None,
                                "EyeColor": None,
                                "Bodytype": None,
                                "Clothes": None,
                                "Number": None,
                                "Pos": None,
                                "SecondPos": None,
                                "PlayInitor": None,
                                "PlayStyle": None,
                                "PlayType1": None,
                                "PlayType2": None,
                                "PlayType3": None,
                                "PlayType4": None,
                                "SShtIns": None,
                                "SShtCls": None,
                                "SShtMed": None,
                                "SSht3PT": None,
                                "SShtFT": None,
                                "SLayUp": None,
                                "SDunk": None,
                                "SStdDunk": None,
                                "SShtInT": None,
                                "SPstFdaway": None,
                                "SPstHook": None,
                                "SShtOfD": None,
                                "SBallHndl": None,
                                "SOffHDrib": None,
                                "SBallSec": None,
                                "SPass": None,
                                "SBlock": None,
                                "SSteal": None,
                                "SHands": None,
                                "SOnBallD": None,
                                "SOReb": None,
                                "SDReb": None,
                                "SOLowPost": None,
                                "SDLowPost": None,
                                "SOAwar": None,
                                "SDAwar": None,
                                "SConsis": None,
                                "SStamina": None,
                                "SSpeed": None,
                                "SQuick": None,
                                "SStrength": None,
                                "SVertical": None,
                                "SHustle": None,
                                "SDurab": None,
                                "SPOT": None,
                                "SEmotion": None,
                                "SigSkill1": None,
                                "SigSkill2": None,
                                "SigSkill3": None,
                                "SigSkill4": None,
                                "SigSkill5": None,
                                "TShtTend": None,
                                "TInsShots": None,
                                "TCloseSht": None,
                                "TMidShots": None,
                                "T3PTShots": None,
                                "TPutbacks": None,
                                "TDriveLn": None,
                                "TPullUp": None,
                                "TPumpFake": None,
                                "TTrplThrt": None,
                                "TTTShot": None,
                                "TNoTT": None,
                                "TStrghtDr": None,
                                "TSizeUp": None,
                                "THesitat": None,
                                "TDriveRvL": None,
                                "TCrossov": None,
                                "TSpin": None,
                                "TStepBack": None,
                                "THalfSpin": None,
                                "TDblCross": None,
                                "TBhndBack": None,
                                "THesCross": None,
                                "TInAndOut": None,
                                "TDPSimpDr": None,
                                "TAttackB": None,
                                "TPassOut": None,
                                "THopStep": None,
                                "TSpinLUp": None,
                                "TEuroStep": None,
                                "TRunner": None,
                                "TFadeaway": None,
                                "TStpbJmpr": None,
                                "TSpinJmpr": None,
                                "TDunkvLU": None,
                                "TAlleyOop": None,
                                "TUseGlass": None,
                                "TDrawFoul": None,
                                "TStpThrgh": None,
                                "TVShCrash": None,
                                "TUsePick": None,
                                "TSetPick": None,
                                "TIsolat": None,
                                "TUseOBScr": None,
                                "TSetOBScr": None,
                                "TSpotUp": None,
                                "TPostUp": None,
                                "TGiveGo": None,
                                "TTouches": None,
                                "TPostSpn": None,
                                "TPostDrv": None,
                                "TPostAgBd": None,
                                "TLeavePost": None,
                                "TPostDrpSt": None,
                                "TPostFaceU": None,
                                "TPostBDown": None,
                                "TPostShots": None,
                                "TPostHook": None,
                                "TPostFdawy": None,
                                "TPostShmSh": None,
                                "TPostHopSh": None,
                                "TFlshPass": None,
                                "TThrowAO": None,
                                "THardFoul": None,
                                "TTakeChrg": None,
                                "TPassLane": None,
                                "TOnBalStl": None,
                                "TContShot": None,
                                "TCommFoul": None,
                                "HIso3PLft": None,
                                "HIso3PCtr": None,
                                "HIso3PRgt": None,
                                "HIsoHPLft": None,
                                "HIsoHPCtr": None,
                                "HIsoHPRgt": None,
                                "HP_rLCrnr": None,
                                "HP_rLWing": None,
                                "HP_rTopOA": None,
                                "HP_rRWing": None,
                                "HP_rRCrnr": None,
                                "HSpt3PLCr": None,
                                "HSpt3PLWg": None,
                                "HSpt3PTop": None,
                                "HSpt3PRWg": None,
                                "HSpt3PRCr": None,
                                "HSptMdLBl": None,
                                "HSptMdLWg": None,
                                "HSptMdCtr": None,
                                "HSptMdRWg": None,
                                "HSptMdRBl": None,
                                "HPstRHigh": None,
                                "HPstRLow": None,
                                "HPstLHigh": None,
                                "HPstLLow": None,
                                "HZ1": None,
                                "HZ2": None,
                                "HZ3": None,
                                "HZ4": None,
                                "HZ5": None,
                                "HZ6": None,
                                "HZ7": None,
                                "HZ8": None,
                                "HZ9": None,
                                "HZ10": None,
                                "HZ11": None,
                                "HZ12": None,
                                "HZ13": None,
                                "HZ14": None,
                                "AShtForm": None,
                                "AShtBase": None,
                                "AFadeaway": None,
                                "AContestd": None,
                                "AEscDrPlU": None,
                                "ARunner": None,
                                "AFreeT": None,
                                "ADrPullUp": None,
                                "ASpinJmpr": None,
                                "AHopJmpr": None,
                                "APstFade": None,
                                "APstHook": None,
                                "APstHopSh": None,
                                "APstShmSh": None,
                                "APstDrvStB": None,
                                "APstSpnStB": None,
                                "APstPrtct": None,
                                "APstPrtSpn": None,
                                "AIsoCross": None,
                                "AIsoBhBck": None,
                                "AIsoSpin": None,
                                "AIsoHesit": None,
                                "ALayUp": None,
                                "AGoToDunk": None,
                                "ADunk2": None,
                                "ADunk3": None,
                                "ADunk4": None,
                                "ADunk5": None,
                                "ADunk6": None,
                                "ADunk7": None,
                                "ADunk8": None,
                                "ADunk9": None,
                                "ADunk10": None,
                                "ADunk11": None,
                                "ADunk12": None,
                                "ADunk13": None,
                                "ADunk14": None,
                                "ADunk15": None,
                                "AIntHLght": None,
                                "AIntPreG1": None,
                                "AIntPreG2": None,
                                "AIntPreT1": None,
                                "AIntPreT2": None,
                                "GHeadband": None,
                                "GHdbndLg": None,
                                "GUndrshrt": None,
                                "GUndrsCol": None,
                                "GLeftArm": None,
                                "GLArmCol": None,
                                "GLeftElb": None,
                                "GLElbCol": None,
                                "GLeftWrst": None,
                                "GLWrstC1": None,
                                "GLWrstC2": None,
                                "GLeftFngr": None,
                                "GLFngrCol": None,
                                "GRghtArm": None,
                                "GRArmCol": None,
                                "GRghtElb": None,
                                "GRElbCol": None,
                                "GRghtWrst": None,
                                "GRWrstC1": None,
                                "GRWrstC2": None,
                                "GRghtFngr": None,
                                "GRFngrCol": None,
                                "GPresShrt": None,
                                "GPrsShCol": None,
                                "GLeftLeg": None,
                                "GLLegCol": None,
                                "GLeftKnee": None,
                                "GLKneeCol": None,
                                "GLeftAnkl": None,
                                "GLAnklCol": None,
                                "GRghtLeg": None,
                                "GRLegCol": None,
                                "GRghtKnee": None,
                                "GRKneeCol": None,
                                "GRghtAnkl": None,
                                "GRAnklCol": None,
                                "GSockLngh": None,
                                "GShsBrLck": None,
                                "GShsBrand": None,
                                "GShsModel": None,
                                "GShsUCusC": None,
                                "GShsTHC1": None,
                                "GShsTHC2": None,
                                "GShsTAC1": None,
                                "GShsTAC2": None,
                                "GShsHCol1": None,
                                "GShsHCol2": None,
                                "GShsHCol3": None,
                                "GShsACol1": None,
                                "GShsACol2": None,
                                "GShsACol3": None,
                                "CAP_FaceT": None,
                                "CAP_Hstl": None,
                                "CAP_Hcol": None,
                                "CAP_Hlen": None,
                                "CAP_BStyle": None,
                                "CAP_Moust": None,
                                "CAP_Goatee": None,
                                "CAP_Fhcol": None,
                                "CAP_Eyebr": None,
                                "CAP_T_LftN": None,
                                "CAP_T_LftS": None,
                                "CAP_T_RgtS": None,
                                "CAP_T_LftB": None,
                                "CAP_T_RgtB": None,
                                "CAP_T_LftF": None,
                                "CAP_T_RgtF": None,
                                "HParam1": None,
                                "HParam2": None,
                                "HdBrwHght": None,
                                "HdBrwWdth": None,
                                "HdBrwSlpd": None,
                                "HdNkThck": None,
                                "HdNkFat": None,
                                "HdChnLen": None,
                                "HdChnWdth": None,
                                "HdChnProt": None,
                                "HdJawSqr": None,
                                "HdJawWdth": None,
                                "HdChkHght": None,
                                "HdChkWdth": None,
                                "HdChkFull": None,
                                "HdDefinit": None,
                                "MtULCurve": None,
                                "MtULThick": None,
                                "MtULProtr": None,
                                "MtLLCurve": None,
                                "MtLLThick": None,
                                "MtLLProtr": None,
                                "MtSzHght": None,
                                "MtSzWdth": None,
                                "MtCrvCorn": None,
                                "ErHeight": None,
                                "ErWidth": None,
                                "ErEarLobe": None,
                                "ErTilt": None,
                                "NsNsHght": None,
                                "NsNsWdth": None,
                                "NsNsProtr": None,
                                "NsBnBridge": None,
                                "NsBnDefin": None,
                                "NsBnWdth": None,
                                "NsTipHght": None,
                                "NsTipWdth": None,
                                "NsTipTip": None,
                                "NsTipBnd": None,
                                "NsNtHght": None,
                                "NsNtWdth": None,
                                "EsFrmOpen": None,
                                "EsFrmSpac": None,
                                "EsFrmLwEl": None,
                                "EsFrmUpEl": None,
                                "EsPlcHght": None,
                                "EsPlcWdth": None,
                                "EsPlcRot": None,
                                "EsPlcProt": None,
                                "EsShpOtEl": None,
                                "EsShpInEl": None,
                                "HS_ID": None,
                                "IsRegNBA": None,
                                "IsSpecial": None,
                                "SlotType": None,
                                "IsGener": None,
                                "IsDraftee": None,
                                "IsDrafted": None,
                                "ASA_ID": None,
                                "IsFA": None,
                                "TeamID1": None,
                                "TeamID2": None,
                                "BirthDay": None,
                                "BirthMonth": None,
                                "BirthYear": None,
                                "YearsPro": None,
                                "CollegeID": None,
                                "DraftedBy": None,
                                "DraftYear": None,
                                "DraftRound": None,
                                "DraftPos": None,
                                "Personality": None,
                                "Play4Winner": None,
                                "FinSecurity": None,
                                "Loyalty": None,
                                "PeakAgeS": None,
                                "PeakAgeE": None,
                                "MinsAsg": None,
                                "Morale": None,
                                "Fatigue": None,
                                "FARestr": None,
                                "CtrThoughts": None,
                                "InjDaysLeft": None,
                                "InjType": None,
                                "StatY0": None,
                                "StatY1": None,
                                "StatY2": None,
                                "StatY3": None,
                                "StatY4": None,
                                "StatY5": None,
                                "StatY6": None,
                                "StatY7": None,
                                "StatY8": None,
                                "StatY9": None,
                                "StatY10": None,
                                "StatY11": None,
                                "StatY12": None,
                                "StatY13": None,
                                "StatY14": None,
                                "StatY15": None,
                                "StatY16": None,
                                "StatY17": None,
                                "StatY18": None,
                                "StatY19": None,
                                "StatPOs": None,
                                "GH_CarPts": None,
                                "GH_CarFGM": None,
                                "GH_CarFGA": None,
                                "GH_CarStl": None,
                                "GH_CarBlk": None,
                                "GH_Car3PM": None,
                                "GH_Car3PA": None,
                                "GH_CarFTM": None,
                                "GH_CarFTA": None,
                                "GH_CarOReb": None,
                                "GH_CarDReb": None,
                                "GH_CarRebs": None,
                                "GH_CarAst": None,
                                "GH_SeaPts": None,
                                "GH_SeaFGM": None,
                                "GH_SeaFGA": None,
                                "GH_SeaStl": None,
                                "GH_SeaBlk": None,
                                "GH_Sea3PM": None,
                                "GH_Sea3PA": None,
                                "GH_SeaFTM": None,
                                "GH_SeaFTA": None,
                                "GH_SeaOReb": None,
                                "GH_SeaDReb": None,
                                "GH_SeaRebs": None,
                                "GH_SeaAst": None,
                                "BirdYears": None,
                                "CClrYears": None,
                                "CRole": None,
                                "COption": None,
                                "CNoTrade": None,
                                "CYear1": None,
                                "CYear2": None,
                                "CYear3": None,
                                "CYear4": None,
                                "CYear5": None,
                                "CYear6": None,
                                "SgndTYWith": None,
                                "YrsForCurT": None,
                                "ExtraValue1": None,
                                "ExtraValue2": None,
                                "ExtraValue3": None,
                                "ExtraValue4": None,
                                "ExtraValue5": None,
                                "ExtraValue6": None,
                                "ExtraValue7": None,
                                "ExtraValue8": None,
                                "ExtraValue9": None,
                                "ExtraValue10": None,
                                "ExtraValue11": None,
                                "ExtraValue12": None,
                                "ExtraValue13": None,
                                "ExtraValue14": None,
                                "ExtraValue15": None,
                                "ExtraValue16": None,
                                "ExtraValue17": None,
                                "ExtraValue18": None,
                                "ExtraValue19": None,
                                "ExtraValue20": None,
                                "ExtraValue21": None,
                                "ExtraValue22": None,
                                "ExtraValue23": None,
                                "ExtraValue24": None,
                                "ExtraValue25": None,
                                "ExtraValue26": None,
                                "ExtraValue27": None,
                                "ExtraValue28": None,
                                "ExtraValue29": None,
                                "ExtraValue30": None,
                                "ExtraValue31": None,
                                "ExtraValue32": None,
                                "ExtraValue33": None,
                                "ExtraValue34": None,
                                "ExtraValue35": None,
                                "ExtraValue36": None,
                                "ExtraValue37": None,
                                "ExtraValue38": None,
                                "ExtraValue39": None,
                                "ExtraValue40": None,
                                "ExtraValue41": None,
                                "ExtraValue42": None,
                                "ExtraValue43": None,
                                "ExtraValue44": None,
                                "ExtraValue45": None,
                                "ExtraValue46": None,
                                "ExtraValue47": None,
                                "ExtraValue48": None,
                                "ExtraValue49": None,
                                "ExtraValue50": None}
        return PLAYER_DICT_TEMPLATE

    insertManyString = "INSERT INTO " + tableName + " ("
    questionMarksString = "VALUES ("
    for key in getPlayerDictTemplate().keys():
        insertManyString += key + ","
        questionMarksString += "?,"
    insertManyString += "SpriteID)"
    questionMarksString += "?)"




    playersList = []
    for playerElement in root:

        thisPlayerDict = getPlayerDictTemplate()
        orderedValuesList = []
        for elementSection in playerElement:
            for singleElement in elementSection:
                if(singleElement.tag not in thisPlayerDict.keys()):
                    print("ERROR: key '" + singleElement.tag + "' exists in XML file, but not in playerDict!")
                    return False
                thisElementValue = singleElement.text
                if(thisElementValue == "None" or thisElementValue is None):
                    thisElementValue = None
                thisPlayerDict[singleElement.tag] = thisElementValue


        for targetElement in thisPlayerDict.keys():
            orderedValuesList.append(thisPlayerDict[targetElement])

        orderedValuesList.append(playerElement.attrib.get("spriteID"))
        playersList.append(tuple(orderedValuesList))


    insertManyString = insertManyString + " " + questionMarksString
    cursor.executemany(insertManyString, playersList)
    conn.commit()
GLOBAL_STAT_LIST = {"LoadedRoster" : "Text",
                    "Mode" : "Integer",
                    "PlayDate" : "Blob",
                    "GameDuration" : "Real",
                    "BallerzScore" : "Integer",
                    "RingersScore" : "Integer",
                    "ExtraValue1" : "Text",
                    "ExtraValue2" : "Text",
                    "ExtraValue3" : "Text",
                    "ExtraValue4" : "Text",
                    "ExtraValue5" : "Text",
                    "ExtraValue6" : "Text",
                    "ExtraValue7" : "Text",
                    "ExtraValue8" : "Text",
                    "ExtraValue9" : "Text",
                    "ExtraValue10" : "Text"}
INDIVIDUAL_STAT_LIST =    {"GameID" : "Integer",
                            "PlayerSlot" : "Integer",
                              "IsActive" : "Integer",
                              "SpriteID" : "Integer",
                              "RosterID" : "Integer",
                              "Points" : "Integer",
                              "DefensiveRebounds" : "Integer",
                              "OffensiveRebounds" : "Integer",
                              "PointsPerAssist" : "Integer",
                              "AssistCount" : "Integer",
                              "Steals" : "Integer",
                              "Blocks" : "Integer",
                              "Turnovers" : "Integer",
                              "InsidesMade" : "Integer",
                              "InsidesAttempted" : "Integer",
                              "ThreesMade" : "Integer",
                              "ThreesAttempted" : "Integer",
                              "Fouls" : "Integer",
                              "Dunks" : "Integer",
                              "Layups" : "Integer",
                              "Unknown1" : "Integer",
                              "Unknown2" : "Integer"}
# This function generates a new, empty Games and PlayerSlots table in the given dbPath.
def genBlankStatsTable(dbPath):
    conn = sqlite3.connect(dbPath)
    cursor = conn.cursor()

    createStatsTable = "CREATE TABLE 'Games' ('GameID' INTEGER NOT NULL UNIQUE,"
    for key in GLOBAL_STAT_LIST.keys():
        createStatsTable += "'" + key + "'" + " " + GLOBAL_STAT_LIST[key] + ","
    createStatsTable += "PRIMARY KEY('GameID'));"

    createSlotsTable = "CREATE TABLE 'PlayerSlots' ('GameID' INTEGER NOT NULL,"
    for key in INDIVIDUAL_STAT_LIST:
        if(key == "GameID"):
            continue
        createSlotsTable += "'" + key + "'" + " " + INDIVIDUAL_STAT_LIST[key] + ","
    createSlotsTable += "FOREIGN KEY (GameID) REFERENCES Games(GameID));"


    cursor.execute(createStatsTable)
    cursor.execute(createSlotsTable)
    conn.commit()
# This function adds all games stored in xmlPath to the given dbPath.
def convertStatsXMLToSQL(xmlPath,dbPath):
    tree = ET.parse(xmlPath)
    root = tree.getroot()

    conn = sqlite3.connect(dbPath)
    cursor = conn.cursor()

    insertGamesString = "INSERT OR REPLACE INTO Games ("
    questionGamesString = "VALUES ("
    for key in GLOBAL_STAT_LIST.keys():
        insertGamesString += key + ","
        questionGamesString += "?,"
    insertGamesString = insertGamesString.rstrip(",") + ")"
    questionGamesString = questionGamesString.rstrip(",") + ")"
    insertGamesString = insertGamesString + " " + questionGamesString

    insertSlotsString = "INSERT OR REPLACE INTO PlayerSlots ("
    questionSlotsString = "VALUES ("
    for key in INDIVIDUAL_STAT_LIST.keys():
        insertSlotsString += key + ","
        questionSlotsString += "?,"
    insertSlotsString = insertSlotsString.rstrip(",") + ")"
    questionSlotsString = questionSlotsString.rstrip(",") + ")"
    insertSlotsString = insertSlotsString + " " + questionSlotsString


    allGamesData = []
    allSlotsData = []
    for game in root:
        thisGameData = []
        for elementToFind in GLOBAL_STAT_LIST:
            thisGameData.append(game.find(elementToFind).text)
        allGamesData.append(tuple(thisGameData))

        for i in range(10):
            thisSlotData = []
            thisSlot = game.xpath(".//SLOT[@position=" + str(i + 1) + "]")[0]
            for elementToFind in INDIVIDUAL_STAT_LIST:
                if(elementToFind == "GameID"):
                    thisSlotData.append(int(game.attrib.get("ID")) + 1)
                elif(elementToFind == "PlayerSlot"):
                    thisSlotData.append(i + 1)
                else:
                    thisSlotData.append(thisSlot.find(elementToFind).text)
            allSlotsData.append(tuple(thisSlotData))

    cursor.executemany(insertGamesString,allGamesData)
    cursor.executemany(insertSlotsString,allSlotsData)
    conn.commit()



# This method will add specific, Roster defined players to Players.db based off a given Roster,
# as well as a range of RosterIDs to read from. If no start/
# endID is specified, it simply adds all players. If an array of individual values
# is supplied, it will only read those values into Players.xml.
def readRosterCSVIntoPlayersFile(rosterName,startID=0,endID=1515,specificValues=None,dataStorageObject=None):
    if(dataStorageObject is None):
        d = DataStorage.DataStorage()
    else:
        d = dataStorageObject
    if(specificValues is None):
        for rosterID in range(startID,endID+1):
            player = d.csv_GetSinglePlayerDict(rosterName,rosterID)
            print(f"Now loading {d.csvRosterDict['Players'][rosterID][3]} {d.csvRosterDict['Players'][rosterID][2]}")
            d.playersDB_UpdatePlayer(spriteID=d.playersDB_AddBlankPlayer(),playerDictionary=player)
    else:
        for rosterID in specificValues:
            player = d.csv_GetSinglePlayerDict(rosterName,rosterID)
            print(f"Now loading {d.csvRosterDict['Players'][rosterID][3]} {d.csvRosterDict['Players'][rosterID][2]}")
            d.playersDB_UpdatePlayer(spriteID=d.playersDB_AddBlankPlayer(),playerDictionary=player)
    d.playersDB_Execute()

# This function sets up a new Roster to be tracked by DataStorage, and creates the
# necessary directory and db files. It also exports the initial roster's CSV files.
# If buildNewRosterFile is true, it also creates and saves the literal roster file in %appdata%.
def trackNewRoster(newRosterName,buildNewRosterFile=False,dataStorageObject=None):
    if(dataStorageObject is None):
        d = DataStorage.DataStorage()
    else:
        d = dataStorageObject

    if(newRosterName in d.csv_GetSavedRosterList()):
        print("Roster already tracked!")
        return False

    if(buildNewRosterFile):
        templateRoster = f"{b.paths.templates}\\BlankRosterTemplate.ROS"
        destinationRoster = f"{b.paths.rosters}\\{newRosterName}.ROS"
        shutil.copy(templateRoster,destinationRoster)

    os.mkdir(f"{b.paths.rosterCSVs}\\{newRosterName}")
    shutil.copy(f"{b.paths.templates}\\SpriteIDs.db",f"{b.paths.rosterCSVs}\\{newRosterName}\\SpriteIDs.db")
    shutil.copy(f"{b.paths.templates}\\rosterSettingsTemplate.cfg",f"{b.paths.rosterCSVs}\\{newRosterName}\\settings.cfg")
    h.exportRedMCCSVs(newRosterName,d)



#genBlankStatsTable(f"{b.paths.databases}\\Stats.db")

'''
#----------------------------------------------------------
#This code block generates an entirely new Players.db file, copying over up to maxSpriteID players
#from an old Players.db file.
#----------------------------------------------------------

maxSpriteID = 355
oldPlayersFilePath = f"{b.paths.databases}\\PlayersPostPMod.db"
newPlayersFilePath = f"{b.paths.databases}\\PlayersEpic.db"

genBlankPlayersTable(dbPath=newPlayersFilePath)
dOld = DataStorage.DataStorage(playersPathOverride=oldPlayersFilePath)
dNew = DataStorage.DataStorage(playersPathOverride=newPlayersFilePath)
allPlayers = []
for i in range(maxSpriteID):
    thisPlayer = dOld.players[i]
    allPlayers.append(thisPlayer)
for thisPlayer in allPlayers:
    thisPlayer.overrideSpriteID(-1)
    print(f"-{thisPlayer['First_Name']} {thisPlayer['Last_Name']}")
    newID = dNew.playersDB_AddPlayer(player=thisPlayer)
dNew.playersDB_UploadPlayers()
'''