from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSignal
from PyQt5.QtGui import QStandardItemModel, QStandardItem
import sys
import DataStorage
import Helpers
import BaseFunctions as b
import Player

class Ui_defensiveAttributesWidget(object):
    def __init__(self,baseWidget = None):
        self.baseWidget = baseWidget
        self.viewedPlayer = Player.Player()

    def setupUi(self,newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget

        self.baseWidget.setObjectName("defensiveAttributesWidget")
        self.baseWidget.resize(271, 108)
        self.defensiveLabel = QtWidgets.QLabel(self.baseWidget)
        self.defensiveLabel.setGeometry(QtCore.QRect(5, 0, 47, 13))
        self.defensiveLabel.setObjectName("defensiveLabel")
        self.offensiveReboundLabel = QtWidgets.QLabel(self.baseWidget)
        self.offensiveReboundLabel.setGeometry(QtCore.QRect(10, 20, 55, 13))
        self.offensiveReboundLabel.setObjectName("offensiveReboundLabel")
        self.line = QtWidgets.QFrame(self.baseWidget)
        self.line.setGeometry(QtCore.QRect(56, 0, 206, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.defensiveReboundLabel = QtWidgets.QLabel(self.baseWidget)
        self.defensiveReboundLabel.setGeometry(QtCore.QRect(10, 40, 55, 13))
        self.defensiveReboundLabel.setObjectName("defensiveReboundLabel")
        self.strengthLabel = QtWidgets.QLabel(self.baseWidget)
        self.strengthLabel.setGeometry(QtCore.QRect(10, 60, 55, 13))
        self.strengthLabel.setObjectName("strengthLabel")
        self.blockLabel = QtWidgets.QLabel(self.baseWidget)
        self.blockLabel.setGeometry(QtCore.QRect(10, 80, 55, 13))
        self.blockLabel.setObjectName("blockLabel")
        self.blockAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.blockAttributeLabel.setGeometry(QtCore.QRect(70, 80, 20, 13))
        self.blockAttributeLabel.setObjectName("blockAttributeLabel")
        self.strengthAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.strengthAttributeLabel.setGeometry(QtCore.QRect(70, 60, 20, 13))
        self.strengthAttributeLabel.setObjectName("strengthAttributeLabel")
        self.defensiveReboundAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.defensiveReboundAttributeLabel.setGeometry(QtCore.QRect(70, 40, 20, 13))
        self.defensiveReboundAttributeLabel.setObjectName("defensiveReboundAttributeLabel")
        self.offensiveReboundAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.offensiveReboundAttributeLabel.setGeometry(QtCore.QRect(70, 20, 20, 13))
        self.offensiveReboundAttributeLabel.setObjectName("offensiveReboundAttributeLabel")
        self.line_2 = QtWidgets.QFrame(self.baseWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 36, 80, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.baseWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 56, 80, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.baseWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 76, 80, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.baseWidget)
        self.line_5.setGeometry(QtCore.QRect(10, 100, 250, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.onBallDefenseLabel = QtWidgets.QLabel(self.baseWidget)
        self.onBallDefenseLabel.setGeometry(QtCore.QRect(100, 20, 55, 13))
        self.onBallDefenseLabel.setObjectName("onBallDefenseLabel")
        self.defensiveAwarenessLabel = QtWidgets.QLabel(self.baseWidget)
        self.defensiveAwarenessLabel.setGeometry(QtCore.QRect(100, 60, 55, 13))
        self.defensiveAwarenessLabel.setObjectName("defensiveAwarenessLabel")
        self.lowPostDefenseAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.lowPostDefenseAttributeLabel.setGeometry(QtCore.QRect(160, 40, 20, 13))
        self.lowPostDefenseAttributeLabel.setObjectName("lowPostDefenseAttributeLabel")
        self.line_6 = QtWidgets.QFrame(self.baseWidget)
        self.line_6.setGeometry(QtCore.QRect(100, 76, 80, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.defensiveAwarenessAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.defensiveAwarenessAttributeLabel.setGeometry(QtCore.QRect(160, 60, 20, 13))
        self.defensiveAwarenessAttributeLabel.setObjectName("defensiveAwarenessAttributeLabel")
        self.onBallDefenseAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.onBallDefenseAttributeLabel.setGeometry(QtCore.QRect(160, 20, 20, 13))
        self.onBallDefenseAttributeLabel.setObjectName("onBallDefenseAttributeLabel")
        self.line_7 = QtWidgets.QFrame(self.baseWidget)
        self.line_7.setGeometry(QtCore.QRect(100, 36, 80, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.lowPostDefenseLabel = QtWidgets.QLabel(self.baseWidget)
        self.lowPostDefenseLabel.setGeometry(QtCore.QRect(100, 40, 55, 13))
        self.lowPostDefenseLabel.setObjectName("lowPostDefenseLabel")
        self.line_8 = QtWidgets.QFrame(self.baseWidget)
        self.line_8.setGeometry(QtCore.QRect(100, 56, 80, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_10 = QtWidgets.QFrame(self.baseWidget)
        self.line_10.setGeometry(QtCore.QRect(85, 15, 20, 81))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.baseWidget)
        self.line_11.setGeometry(QtCore.QRect(175, 15, 20, 81))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.baseWidget.setWindowTitle(_translate("defensiveAttributesWidget", "defensiveAttributesWidget"))
        self.defensiveLabel.setText(_translate("defensiveAttributesWidget", "Defensive"))
        self.offensiveReboundLabel.setText(_translate("defensiveAttributesWidget", "O Rebound"))
        self.defensiveReboundLabel.setText(_translate("defensiveAttributesWidget", "D Rebound"))
        self.strengthLabel.setText(_translate("defensiveAttributesWidget", "Stength"))
        self.blockLabel.setText(_translate("defensiveAttributesWidget", "Block"))
        self.blockAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SBlock']}"))
        self.strengthAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SStrength']}"))
        self.defensiveReboundAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SOReb']}"))
        self.offensiveReboundAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SDReb']}"))
        self.onBallDefenseLabel.setText(_translate("defensiveAttributesWidget", "On Ball D"))
        self.defensiveAwarenessLabel.setText(_translate("defensiveAttributesWidget", "D Aware"))
        self.lowPostDefenseAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SDLowPost']}"))
        self.defensiveAwarenessAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SDAwar']}"))
        self.onBallDefenseAttributeLabel.setText(_translate("defensiveAttributesWidget", f"{self.viewedPlayer['SOnBallD']}"))
        self.lowPostDefenseLabel.setText(_translate("defensiveAttributesWidget", "Low Post D"))

    def updatePlayer(self,player : Player.Player = Player.Player()):
        self.viewedPlayer = player
        self.retranslateUi()
class Ui_offensiveAttributesWidget(object):
    def __init__(self,baseWidget = None):
        self.baseWidget = baseWidget
        self.viewedPlayer = Player.Player()

    def setupUi(self,newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget

        self.baseWidget.setObjectName("offensiveAttributesWidget")
        self.baseWidget.resize(271, 108)
        self.offensiveLabel = QtWidgets.QLabel(self.baseWidget)
        self.offensiveLabel.setGeometry(QtCore.QRect(5, 0, 47, 13))
        self.offensiveLabel.setObjectName("offensiveLabel")
        self.shotThreeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotThreeLabel.setGeometry(QtCore.QRect(10, 20, 55, 13))
        self.shotThreeLabel.setObjectName("shotThreeLabel")
        self.line = QtWidgets.QFrame(self.baseWidget)
        self.line.setGeometry(QtCore.QRect(56, 0, 206, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.shotMediumLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotMediumLabel.setGeometry(QtCore.QRect(10, 40, 55, 13))
        self.shotMediumLabel.setObjectName("shotMediumLabel")
        self.shotCloseLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotCloseLabel.setGeometry(QtCore.QRect(10, 60, 55, 13))
        self.shotCloseLabel.setObjectName("shotCloseLabel")
        self.shootInTrafficLabel = QtWidgets.QLabel(self.baseWidget)
        self.shootInTrafficLabel.setGeometry(QtCore.QRect(10, 80, 55, 13))
        self.shootInTrafficLabel.setObjectName("shootInTrafficLabel")
        self.shotInTrafficAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotInTrafficAttributeLabel.setGeometry(QtCore.QRect(70, 80, 20, 13))
        self.shotInTrafficAttributeLabel.setObjectName("shotInTrafficAttributeLabel")
        self.shotCloseAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotCloseAttributeLabel.setGeometry(QtCore.QRect(70, 60, 20, 13))
        self.shotCloseAttributeLabel.setObjectName("shotCloseAttributeLabel")
        self.shotMediumAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotMediumAttributeLabel.setGeometry(QtCore.QRect(70, 40, 20, 13))
        self.shotMediumAttributeLabel.setObjectName("shotMediumAttributeLabel")
        self.shotThreeAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotThreeAttributeLabel.setGeometry(QtCore.QRect(70, 20, 20, 13))
        self.shotThreeAttributeLabel.setObjectName("shotThreeAttributeLabel")
        self.line_2 = QtWidgets.QFrame(self.baseWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 36, 80, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.baseWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 56, 80, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.baseWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 76, 80, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.baseWidget)
        self.line_5.setGeometry(QtCore.QRect(10, 100, 250, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.shootOffDribbleLabel = QtWidgets.QLabel(self.baseWidget)
        self.shootOffDribbleLabel.setGeometry(QtCore.QRect(100, 20, 55, 13))
        self.shootOffDribbleLabel.setObjectName("shootOffDribbleLabel")
        self.postHookLabel = QtWidgets.QLabel(self.baseWidget)
        self.postHookLabel.setGeometry(QtCore.QRect(100, 60, 55, 13))
        self.postHookLabel.setObjectName("postHookLabel")
        self.postFadeawayAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.postFadeawayAttributeLabel.setGeometry(QtCore.QRect(160, 40, 20, 13))
        self.postFadeawayAttributeLabel.setObjectName("postFadeawayAttributeLabel")
        self.line_6 = QtWidgets.QFrame(self.baseWidget)
        self.line_6.setGeometry(QtCore.QRect(100, 76, 80, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.postHookAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.postHookAttributeLabel.setGeometry(QtCore.QRect(160, 60, 20, 13))
        self.postHookAttributeLabel.setObjectName("postHookAttributeLabel")
        self.shootOffDribbleAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shootOffDribbleAttributeLabel.setGeometry(QtCore.QRect(160, 20, 20, 13))
        self.shootOffDribbleAttributeLabel.setObjectName("shootOffDribbleAttributeLabel")
        self.lowPostOffenseLabel = QtWidgets.QLabel(self.baseWidget)
        self.lowPostOffenseLabel.setGeometry(QtCore.QRect(100, 80, 55, 13))
        self.lowPostOffenseLabel.setObjectName("lowPostOffenseLabel")
        self.line_7 = QtWidgets.QFrame(self.baseWidget)
        self.line_7.setGeometry(QtCore.QRect(100, 36, 80, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.postFadeawayLabel = QtWidgets.QLabel(self.baseWidget)
        self.postFadeawayLabel.setGeometry(QtCore.QRect(100, 40, 55, 13))
        self.postFadeawayLabel.setObjectName("postFadeawayLabel")
        self.lowPostOffenseAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.lowPostOffenseAttributeLabel.setGeometry(QtCore.QRect(160, 80, 20, 13))
        self.lowPostOffenseAttributeLabel.setObjectName("lowPostOffenseAttributeLabel")
        self.line_8 = QtWidgets.QFrame(self.baseWidget)
        self.line_8.setGeometry(QtCore.QRect(100, 56, 80, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.consistencyAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.consistencyAttributeLabel.setGeometry(QtCore.QRect(250, 20, 20, 13))
        self.consistencyAttributeLabel.setObjectName("consistencyAttributeLabel")
        self.consistencyLabel = QtWidgets.QLabel(self.baseWidget)
        self.consistencyLabel.setGeometry(QtCore.QRect(190, 20, 55, 13))
        self.consistencyLabel.setObjectName("consistencyLabel")
        self.line_9 = QtWidgets.QFrame(self.baseWidget)
        self.line_9.setGeometry(QtCore.QRect(190, 36, 80, 3))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.baseWidget)
        self.line_10.setGeometry(QtCore.QRect(85, 15, 20, 81))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.baseWidget)
        self.line_11.setGeometry(QtCore.QRect(175, 15, 20, 81))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.baseWidget.setWindowTitle(_translate("offensiveAttributesWidget", "offensiveAttributesWidget"))
        self.offensiveLabel.setText(_translate("offensiveAttributesWidget", "Offensive"))
        self.shotThreeLabel.setText(_translate("offensiveAttributesWidget", "Shot 3pt"))
        self.shotMediumLabel.setText(_translate("offensiveAttributesWidget", "Shot Med"))
        self.shotCloseLabel.setText(_translate("offensiveAttributesWidget", "Shot Cls"))
        self.shootInTrafficLabel.setText(_translate("offensiveAttributesWidget", "In Traffic"))
        self.shotInTrafficAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SShtInT']}"))
        self.shotCloseAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SShtCls']}"))
        self.shotMediumAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SShtMed']}"))
        self.shotThreeAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SSht3PT']}"))
        self.shootOffDribbleLabel.setText(_translate("offensiveAttributesWidget", "Off Dribble"))
        self.postHookLabel.setText(_translate("offensiveAttributesWidget", "PHook"))
        self.postFadeawayAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SPstFdaway']}"))
        self.postHookAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SPstHook']}"))
        self.shootOffDribbleAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SShtOfD']}"))
        self.lowPostOffenseLabel.setText(_translate("offensiveAttributesWidget", "LP Offense"))
        self.postFadeawayLabel.setText(_translate("offensiveAttributesWidget", "PFadeaway"))
        self.lowPostOffenseAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SOLowPost']}"))
        self.consistencyAttributeLabel.setText(_translate("offensiveAttributesWidget", f"{self.viewedPlayer['SConsis']}"))
        self.consistencyLabel.setText(_translate("offensiveAttributesWidget", "Consistent"))

    def updatePlayer(self,player : Player.Player = Player.Player()):
        self.viewedPlayer = player
        self.retranslateUi()
class Ui_controlAttributesWidget(object):
    def __init__(self,baseWidget = None):
        self.baseWidget = baseWidget
        self.viewedPlayer = Player.Player()

    def setupUi(self,newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget

        self.baseWidget.setObjectName("controlAttributesWidget")
        self.baseWidget.resize(271, 108)
        self.controlLabel = QtWidgets.QLabel(self.baseWidget)
        self.controlLabel.setGeometry(QtCore.QRect(5, 0, 47, 13))
        self.controlLabel.setObjectName("controlLabel")
        self.ballHandlingLabel = QtWidgets.QLabel(self.baseWidget)
        self.ballHandlingLabel.setGeometry(QtCore.QRect(10, 20, 55, 13))
        self.ballHandlingLabel.setObjectName("ballHandlingLabel")
        self.line = QtWidgets.QFrame(self.baseWidget)
        self.line.setGeometry(QtCore.QRect(41, 0, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ballSecurityLabel = QtWidgets.QLabel(self.baseWidget)
        self.ballSecurityLabel.setGeometry(QtCore.QRect(10, 40, 55, 13))
        self.ballSecurityLabel.setObjectName("ballSecurityLabel")
        self.handsLabel = QtWidgets.QLabel(self.baseWidget)
        self.handsLabel.setGeometry(QtCore.QRect(10, 60, 55, 13))
        self.handsLabel.setObjectName("handsLabel")
        self.passLabel = QtWidgets.QLabel(self.baseWidget)
        self.passLabel.setGeometry(QtCore.QRect(10, 80, 55, 13))
        self.passLabel.setObjectName("passLabel")
        self.passAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.passAttributeLabel.setGeometry(QtCore.QRect(70, 80, 20, 13))
        self.passAttributeLabel.setObjectName("passAttributeLabel")
        self.handsAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.handsAttributeLabel.setGeometry(QtCore.QRect(70, 60, 20, 13))
        self.handsAttributeLabel.setObjectName("handsAttributeLabel")
        self.ballSecurityAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.ballSecurityAttributeLabel.setGeometry(QtCore.QRect(70, 40, 20, 13))
        self.ballSecurityAttributeLabel.setObjectName("ballSecurityAttributeLabel")
        self.ballHandlingAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.ballHandlingAttributeLabel.setGeometry(QtCore.QRect(70, 20, 20, 13))
        self.ballHandlingAttributeLabel.setObjectName("ballHandlingAttributeLabel")
        self.line_2 = QtWidgets.QFrame(self.baseWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 36, 80, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.baseWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 56, 80, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.baseWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 76, 80, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.baseWidget)
        self.line_5.setGeometry(QtCore.QRect(10, 100, 250, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.offHandDribblingLabel = QtWidgets.QLabel(self.baseWidget)
        self.offHandDribblingLabel.setGeometry(QtCore.QRect(100, 20, 55, 13))
        self.offHandDribblingLabel.setObjectName("offHandDribblingLabel")
        self.speedLabel = QtWidgets.QLabel(self.baseWidget)
        self.speedLabel.setGeometry(QtCore.QRect(100, 60, 55, 13))
        self.speedLabel.setObjectName("speedLabel")
        self.stealAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.stealAttributeLabel.setGeometry(QtCore.QRect(160, 40, 20, 13))
        self.stealAttributeLabel.setObjectName("stealAttributeLabel")
        self.line_6 = QtWidgets.QFrame(self.baseWidget)
        self.line_6.setGeometry(QtCore.QRect(100, 76, 80, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.speedAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.speedAttributeLabel.setGeometry(QtCore.QRect(160, 60, 20, 13))
        self.speedAttributeLabel.setObjectName("speedAttributeLabel")
        self.offHandDribblingAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.offHandDribblingAttributeLabel.setGeometry(QtCore.QRect(160, 20, 20, 13))
        self.offHandDribblingAttributeLabel.setObjectName("offHandDribblingAttributeLabel")
        self.quicknessLabel = QtWidgets.QLabel(self.baseWidget)
        self.quicknessLabel.setGeometry(QtCore.QRect(100, 80, 55, 13))
        self.quicknessLabel.setObjectName("quicknessLabel")
        self.line_7 = QtWidgets.QFrame(self.baseWidget)
        self.line_7.setGeometry(QtCore.QRect(100, 36, 80, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.stealLabel = QtWidgets.QLabel(self.baseWidget)
        self.stealLabel.setGeometry(QtCore.QRect(100, 40, 55, 13))
        self.stealLabel.setObjectName("stealLabel")
        self.quicknessAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.quicknessAttributeLabel.setGeometry(QtCore.QRect(160, 80, 20, 13))
        self.quicknessAttributeLabel.setObjectName("quicknessAttributeLabel")
        self.line_8 = QtWidgets.QFrame(self.baseWidget)
        self.line_8.setGeometry(QtCore.QRect(100, 56, 80, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.hustleAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.hustleAttributeLabel.setGeometry(QtCore.QRect(250, 20, 20, 13))
        self.hustleAttributeLabel.setObjectName("hustleAttributeLabel")
        self.hustleLabel = QtWidgets.QLabel(self.baseWidget)
        self.hustleLabel.setGeometry(QtCore.QRect(190, 20, 55, 13))
        self.hustleLabel.setObjectName("hustleLabel")
        self.line_9 = QtWidgets.QFrame(self.baseWidget)
        self.line_9.setGeometry(QtCore.QRect(190, 36, 80, 3))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.baseWidget)
        self.line_10.setGeometry(QtCore.QRect(85, 15, 20, 81))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.baseWidget)
        self.line_11.setGeometry(QtCore.QRect(175, 15, 20, 81))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.baseWidget)
        self.line_12.setGeometry(QtCore.QRect(190, 56, 80, 3))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.offensiveAwarenessLabel = QtWidgets.QLabel(self.baseWidget)
        self.offensiveAwarenessLabel.setGeometry(QtCore.QRect(190, 40, 55, 13))
        self.offensiveAwarenessLabel.setObjectName("offensiveAwarenessLabel")
        self.offensiveAwarenessAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.offensiveAwarenessAttributeLabel.setGeometry(QtCore.QRect(250, 40, 20, 13))
        self.offensiveAwarenessAttributeLabel.setObjectName("offensiveAwarenessAttributeLabel")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.baseWidget.setWindowTitle(_translate("controlAttributesWidget", "controlAttributesWidget"))
        self.controlLabel.setText(_translate("controlAttributesWidget", "Control"))
        self.ballHandlingLabel.setText(_translate("controlAttributesWidget", "B Handling"))
        self.ballSecurityLabel.setText(_translate("controlAttributesWidget", "B Security"))
        self.handsLabel.setText(_translate("controlAttributesWidget", "Hands"))
        self.passLabel.setText(_translate("controlAttributesWidget", "Pass"))
        self.passAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SPass']}"))
        self.handsAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SHands']}"))
        self.ballSecurityAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SBallSec']}"))
        self.ballHandlingAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SBallHndl']}"))
        self.offHandDribblingLabel.setText(_translate("controlAttributesWidget", "OH Dribble"))
        self.speedLabel.setText(_translate("controlAttributesWidget", "Speed"))
        self.stealAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SSteal']}"))
        self.speedAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SSpeed']}"))
        self.offHandDribblingAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SOffHDrib']}"))
        self.quicknessLabel.setText(_translate("controlAttributesWidget", "Quickness"))
        self.stealLabel.setText(_translate("controlAttributesWidget", "Steal"))
        self.quicknessAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SQuick']}"))
        self.hustleAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SHustle']}"))
        self.hustleLabel.setText(_translate("controlAttributesWidget", "Hustle"))
        self.offensiveAwarenessLabel.setText(_translate("controlAttributesWidget", "O Aware"))
        self.offensiveAwarenessAttributeLabel.setText(_translate("controlAttributesWidget", f"{self.viewedPlayer['SOAwar']}"))

    def updatePlayer(self,player : Player.Player = Player.Player()):
        self.viewedPlayer = player
        self.retranslateUi()
class Ui_otherAttributesWidget(object):
    def __init__(self,baseWidget = None):
        self.baseWidget = baseWidget
        self.viewedPlayer = Player.Player()

    def setupUi(self,newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget

        self.baseWidget.setObjectName("otherAttributesWidget")
        self.baseWidget.resize(271, 108)
        self.otherLabel = QtWidgets.QLabel(self.baseWidget)
        self.otherLabel.setGeometry(QtCore.QRect(5, 0, 47, 13))
        self.otherLabel.setObjectName("otherLabel")
        self.heightLabel = QtWidgets.QLabel(self.baseWidget)
        self.heightLabel.setGeometry(QtCore.QRect(10, 20, 55, 13))
        self.heightLabel.setObjectName("heightLabel")
        self.verticalLabel = QtWidgets.QLabel(self.baseWidget)
        self.verticalLabel.setGeometry(QtCore.QRect(10, 40, 55, 13))
        self.verticalLabel.setObjectName("verticalLabel")
        self.shotInsideLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotInsideLabel.setGeometry(QtCore.QRect(10, 60, 55, 13))
        self.shotInsideLabel.setObjectName("shotInsideLabel")
        self.dunkLabel = QtWidgets.QLabel(self.baseWidget)
        self.dunkLabel.setGeometry(QtCore.QRect(10, 80, 55, 13))
        self.dunkLabel.setObjectName("dunkLabel")
        self.dunkAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.dunkAttributeLabel.setGeometry(QtCore.QRect(70, 80, 20, 13))
        self.dunkAttributeLabel.setObjectName("dunkAttributeLabel")
        self.shotInsideAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.shotInsideAttributeLabel.setGeometry(QtCore.QRect(70, 60, 20, 13))
        self.shotInsideAttributeLabel.setObjectName("shotInsideAttributeLabel")
        self.verticalAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.verticalAttributeLabel.setGeometry(QtCore.QRect(70, 40, 20, 13))
        self.verticalAttributeLabel.setObjectName("verticalAttributeLabel")
        self.heightAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.heightAttributeLabel.setGeometry(QtCore.QRect(70, 20, 20, 13))
        self.heightAttributeLabel.setObjectName("heightAttributeLabel")
        self.line_2 = QtWidgets.QFrame(self.baseWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 36, 80, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.baseWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 56, 80, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.baseWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 76, 80, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.baseWidget)
        self.line_5.setGeometry(QtCore.QRect(10, 100, 250, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.standingDunkLabel = QtWidgets.QLabel(self.baseWidget)
        self.standingDunkLabel.setGeometry(QtCore.QRect(100, 20, 55, 13))
        self.standingDunkLabel.setObjectName("standingDunkLabel")
        self.standingDunkAttributeLabel = QtWidgets.QLabel(self.baseWidget)
        self.standingDunkAttributeLabel.setGeometry(QtCore.QRect(160, 20, 20, 13))
        self.standingDunkAttributeLabel.setObjectName("standingDunkAttributeLabel")
        self.line_7 = QtWidgets.QFrame(self.baseWidget)
        self.line_7.setGeometry(QtCore.QRect(100, 36, 80, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_10 = QtWidgets.QFrame(self.baseWidget)
        self.line_10.setGeometry(QtCore.QRect(85, 15, 20, 81))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.baseWidget)
        self.line_11.setGeometry(QtCore.QRect(175, 15, 20, 81))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line = QtWidgets.QFrame(self.baseWidget)
        self.line.setGeometry(QtCore.QRect(38, 0, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.baseWidget.setWindowTitle(_translate("otherAttributesWidget", "otherAttributesWidget"))
        self.otherLabel.setText(_translate("otherAttributesWidget", "Other"))
        self.heightLabel.setText(_translate("otherAttributesWidget", "Height"))
        self.verticalLabel.setText(_translate("otherAttributesWidget", "Vertical"))
        self.shotInsideLabel.setText(_translate("otherAttributesWidget", "Shot Ins"))
        self.dunkLabel.setText(_translate("otherAttributesWidget", "Dunk"))
        self.dunkAttributeLabel.setText(_translate("otherAttributesWidget", f"{self.viewedPlayer['SDunk']}"))
        self.shotInsideAttributeLabel.setText(_translate("otherAttributesWidget", f"{self.viewedPlayer['SShtIns']}"))
        self.verticalAttributeLabel.setText(_translate("otherAttributesWidget", f"{self.viewedPlayer['SVertical']}"))
        self.heightAttributeLabel.setText(_translate("otherAttributesWidget", f"{self.viewedPlayer['HeightFt']}"))
        self.standingDunkLabel.setText(_translate("otherAttributesWidget", "Stand Dunk"))
        self.standingDunkAttributeLabel.setText(_translate("otherAttributesWidget", f"{self.viewedPlayer['SStdDunk']}"))

    def updatePlayer(self,player : Player.Player = Player.Player()):
        self.viewedPlayer = player
        self.retranslateUi()

class Ui_searchWidget(QObject):
    playerSelected = pyqtSignal(object)

    def __init__(self,baseWidget = None):
        super().__init__()
        self.baseWidget = baseWidget
        self.allPlayersList = []
        self.updatePlayerList()

        self.currentSelection = None


    def setupUi(self,newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget

        self.baseWidget.setObjectName("searchWidget")
        self.baseWidget.resize(312, 200)
        self.searchEntry = QtWidgets.QLineEdit(self.baseWidget)
        self.searchEntry.setGeometry(QtCore.QRect(50, 10, 171, 21))
        self.searchEntry.setText("")
        self.searchEntry.setObjectName("searchEntry")
        self.searchType = QtWidgets.QComboBox(self.baseWidget)
        self.searchType.setGeometry(QtCore.QRect(230, 10, 71, 21))
        self.searchType.setObjectName("searchType")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchLabel = QtWidgets.QLabel(self.baseWidget)
        self.searchLabel.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.searchLabel.setObjectName("searchLabel")

        self.resultList = QtWidgets.QListView(self.baseWidget)
        self.resultList.setGeometry(QtCore.QRect(10, 40, 211, 151))
        self.resultList.setObjectName("resultList")
        self.listModel = QStandardItemModel(self.baseWidget)
        self.resultList.setModel(self.listModel)
        self.resultList.selectionModel().selectionChanged.connect(self.onItemSelected)

        self.searchPlayerButton = QtWidgets.QCommandLinkButton(self.baseWidget)
        self.searchPlayerButton.setGeometry(QtCore.QRect(240, 140, 61, 41))
        self.searchPlayerButton.setObjectName("searchPlayerButton")


        # Connect searchEntry's textChanged signal to updateResults
        self.searchEntry.textChanged.connect(self.updateResults)
        self.updateResults("")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.baseWidget.setWindowTitle(_translate("searchWidget", "searchWidget"))
        self.searchType.setItemText(0, _translate("searchWidget", "Player"))
        self.searchType.setItemText(1, _translate("searchWidget", "Gauntlet"))
        self.searchType.setItemText(2, _translate("searchWidget", "Team"))
        self.searchType.setItemText(3, _translate("searchWidget", "Faction"))
        self.searchType.setItemText(4, _translate("searchWidget", "CEO"))
        self.searchType.setItemText(5, _translate("searchWidget", "New"))
        self.searchLabel.setText(_translate("searchWidget", "Search:"))
        self.searchPlayerButton.setText(_translate("searchWidget", "GO"))

    # This method simply updates the internal results of the search widget based on the
    # text given.
    def updateResults(self, text):
        # Clear the current items in the list model
        self.listModel.clear()

        # Search for players that match the text and add them to the list model
        for player in self.allPlayersList:
            playerFullName = f"{player['First_Name']} {player['Last_Name']}"
            if text.lower() in playerFullName.lower():
                item = QStandardItem(playerFullName)
                item.setData(player,~QtCore.Qt.UserRole)
                item.setFlags(item.flags() & ~QtCore.Qt.ItemIsEditable)
                self.listModel.appendRow(item)

    # This method populates the search menu with ALL players listed in Players.py.
    def updatePlayerList(self):
        d = DataStorage.DataStorage(openCSVFiles=False,openStatsTable=False,openGauntletTable=False)

        allPlayers = []
        for i in range(1,d.playersDB_GetPlayerCount()+1):
            allPlayers.append(d.playersDB_GetPlayer(spriteID=i))

        allPlayers.sort()
        self.allPlayersList = allPlayers

    # This method updates the "currentSelection" member with the currently selected player for
    # easy access.
    def onItemSelected(self, selected, deselected):
        # Get the QModelIndex of the currently selected item
        index = self.resultList.selectionModel().currentIndex()

        # Get the QStandardItem associated with this index
        item = self.listModel.itemFromIndex(index)

        # Fetch the player object associated with this item
        player = item.data(~QtCore.Qt.UserRole)

        #selected_index = self.listView.selectionModel().currentIndex()
        #selected_player = selected_index.data(QtCore.Qt.UserRole)
        self.playerSelected.emit(player)  # Emit the signal with the selected player
        self.currentSelection = player

class Ui_playerResultWidget(object):
    def setupUi(self, playerResultWidget):
        playerResultWidget.setObjectName("playerResultWidget")
        playerResultWidget.resize(313, 793)
        self.playerNameLabel = QtWidgets.QLabel(playerResultWidget)
        self.playerNameLabel.setGeometry(QtCore.QRect(50, -20, 211, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerNameLabel.sizePolicy().hasHeightForWidth())
        self.playerNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.playerNameLabel.setFont(font)
        self.playerNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.playerNameLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.playerNameLabel.setTextFormat(QtCore.Qt.PlainText)
        self.playerNameLabel.setScaledContents(False)
        self.playerNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerNameLabel.setWordWrap(True)
        self.playerNameLabel.setObjectName("playerNameLabel")
        self.archetypeLabel = QtWidgets.QLabel(playerResultWidget)
        self.archetypeLabel.setGeometry(QtCore.QRect(68, 50, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.archetypeLabel.sizePolicy().hasHeightForWidth())
        self.archetypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.archetypeLabel.setFont(font)
        self.archetypeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.archetypeLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.archetypeLabel.setTextFormat(QtCore.Qt.PlainText)
        self.archetypeLabel.setScaledContents(False)
        self.archetypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.archetypeLabel.setWordWrap(True)
        self.archetypeLabel.setObjectName("archetypeLabel")
        self.rarityLabel = QtWidgets.QLabel(playerResultWidget)
        self.rarityLabel.setGeometry(QtCore.QRect(71, 70, 161, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rarityLabel.sizePolicy().hasHeightForWidth())
        self.rarityLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.rarityLabel.setFont(font)
        self.rarityLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rarityLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rarityLabel.setTextFormat(QtCore.Qt.PlainText)
        self.rarityLabel.setScaledContents(False)
        self.rarityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rarityLabel.setWordWrap(True)
        self.rarityLabel.setObjectName("rarityLabel")
        self.backstoryLabel = QtWidgets.QLabel(playerResultWidget)
        self.backstoryLabel.setGeometry(QtCore.QRect(20, 110, 281, 171))
        self.backstoryLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.backstoryLabel.setWordWrap(True)
        self.backstoryLabel.setObjectName("backstoryLabel")
        self.backstorySeparater = QtWidgets.QFrame(playerResultWidget)
        self.backstorySeparater.setGeometry(QtCore.QRect(20, 280, 281, 20))
        self.backstorySeparater.setFrameShape(QtWidgets.QFrame.HLine)
        self.backstorySeparater.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.backstorySeparater.setObjectName("backstorySeparater")
        self.factionIcon = QtWidgets.QLabel(playerResultWidget)
        self.factionIcon.setGeometry(QtCore.QRect(20, 34, 71, 71))
        self.factionIcon.setText("")
        self.factionIcon.setPixmap(QtGui.QPixmap("FactionIcons/Sludgeservants.png"))
        self.factionIcon.setScaledContents(True)
        self.factionIcon.setObjectName("factionIcon")
        self.artifactIcon = QtWidgets.QLabel(playerResultWidget)
        self.artifactIcon.setGeometry(QtCore.QRect(220, 34, 71, 71))
        self.artifactIcon.setText("")
        self.artifactIcon.setPixmap(QtGui.QPixmap("FactionIcons/American Illegals.jpg"))
        self.artifactIcon.setScaledContents(True)
        self.artifactIcon.setObjectName("artifactIcon")
        self.infoTabs = QtWidgets.QTabWidget(playerResultWidget)
        self.infoTabs.setGeometry(QtCore.QRect(20, 300, 281, 471))
        self.infoTabs.setObjectName("infoTabs")
        self.attributesTab = QtWidgets.QWidget()
        self.attributesTab.setObjectName("attributesTab")
        self.primaryAttributesHolder = QtWidgets.QFrame(self.attributesTab)
        self.primaryAttributesHolder.setGeometry(QtCore.QRect(0, 0, 271, 108))
        self.primaryAttributesHolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.primaryAttributesHolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.primaryAttributesHolder.setObjectName("primaryAttributesHolder")
        self.secondaryAttributesHolder = QtWidgets.QFrame(self.attributesTab)
        self.secondaryAttributesHolder.setGeometry(QtCore.QRect(0, 110, 271, 108))
        self.secondaryAttributesHolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.secondaryAttributesHolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.secondaryAttributesHolder.setObjectName("secondaryAttributesHolder")
        self.tertiaryAttributesHolder = QtWidgets.QFrame(self.attributesTab)
        self.tertiaryAttributesHolder.setGeometry(QtCore.QRect(0, 220, 271, 108))
        self.tertiaryAttributesHolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tertiaryAttributesHolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tertiaryAttributesHolder.setObjectName("tertiaryAttributesHolder")
        self.otherAttributesHolder = QtWidgets.QFrame(self.attributesTab)
        self.otherAttributesHolder.setGeometry(QtCore.QRect(0, 330, 271, 108))
        self.otherAttributesHolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.otherAttributesHolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.otherAttributesHolder.setObjectName("otherAttributesHolder")
        self.infoTabs.addTab(self.attributesTab, "")
        self.statsTab = QtWidgets.QWidget()
        self.statsTab.setObjectName("statsTab")
        self.infoTabs.addTab(self.statsTab, "")

        self.retranslateUi(playerResultWidget)
        self.infoTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(playerResultWidget)

    def retranslateUi(self, playerResultWidget):
        _translate = QtCore.QCoreApplication.translate
        playerResultWidget.setWindowTitle(_translate("playerResultWidget", "playerResultWidget"))
        self.playerNameLabel.setText(_translate("playerResultWidget", "Player Name"))
        self.archetypeLabel.setText(_translate("playerResultWidget", "Archetype"))
        self.rarityLabel.setText(_translate("playerResultWidget", "Rarity"))
        self.backstoryLabel.setText(_translate("playerResultWidget", "This is where the player\'s backstory will go. It will describe their origins, along with many interesting stories which led them to become the person they are today. These are generated by ChatGPT 4.0, and deliver esquisite tales which are faction-based and varied by a multitude of modifiers. So, sit right down and enjoy a heart-warming backstory about Spritopias newest basketball talent. This next sentence is purely to fill more space, as I am trying to see how much room I need to provide to create adequate space for these backstories, but also not too much to leave tons of blank, unusable space where other fun and interesting things can be put."))
        self.infoTabs.setTabText(self.infoTabs.indexOf(self.attributesTab), _translate("playerResultWidget", "Attributes"))
        self.infoTabs.setTabText(self.infoTabs.indexOf(self.statsTab), _translate("playerResultWidget", "Stats"))
# This is our new, more functional class that extends QWidget
class PlayerResultWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(PlayerResultWidget, self).__init__(parent)
        # Initialize the UI
        self.ui = Ui_playerResultWidget()
        self.ui.setupUi(self)

        # Additional setup, connect signals, etc.
        # You can set this up here or in a separate method

    def updatePlayer(self, name):
        self.ui.playerNameLabel.setText(name)

class Ui_playerSearchLeftSidebar(object):
    def __init__(self,baseWidget = None):
        self.baseWidget = baseWidget
        self.searchBarWidget = Ui_searchWidget()
        self.searchBarHolder = QtWidgets.QWidget(self.baseWidget)
        self.searchBarHolder.setGeometry(QtCore.QRect(0, 0, 312, 200))
        self.searchBarHolder.setObjectName("searchBarWidget")
        self.searchBarWidget.setupUi(self.searchBarHolder)

        self.playerLookupHolder = QtWidgets.QWidget(self.baseWidget)
        self.playerLookupHolder.setGeometry(QtCore.QRect(0, 200, 312, 812))
        self.playerLookupHolder.setObjectName("playerLookupWidget")
        self.playerLookupWidget = PlayerResultWidget(self.playerLookupHolder)

    def setupUi(self, newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget

        #self.baseWidget.setObjectName("playerSearchLeftSidebar")
        #self.baseWidget.resize(312, 1012)

        #self.playerLookupWidget.setupUi(self.playerLookupHolder)
        self.playerLookupWidget.updatePlayer(self.searchBarWidget.currentSelection)

        self.searchBarWidget.playerSelected.connect(self.playerLookupWidget.updatePlayer)

        self.retranslateUi(self.baseWidget)
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
class Ui_MainWindow(object):
    def __init__(self,baseWidget = None):
        self.baseWidget = baseWidget

        self.baseWidget.setObjectName("MainWindow")
        self.baseWidget.resize(1920, 1012)
        self.centralwidget = QtWidgets.QWidget(self.baseWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.leftSidebarHolder = QtWidgets.QWidget(self.centralwidget)
        self.leftSidebarHolder.setGeometry(QtCore.QRect(0, 0, 312, 990))
        self.leftSidebarHolder.setObjectName("leftSidebarHolder")

        # TODO THIS SHOULDNT BUILD BY DEFAULT HOMIE
        #self.playerSearchLeftSidebarWidget.setupUi(self.leftSidebarHolder)
        self.playerSearchLeftSidebarWidget = Ui_playerSearchLeftSidebar(self.leftSidebarHolder)

    def setupUi(self,newBaseWidget = None):
        if(newBaseWidget is not None):
            self.baseWidget = newBaseWidget



        self.hubHolder = QtWidgets.QWidget(self.centralwidget)
        self.hubHolder.setGeometry(QtCore.QRect(312, 0, 1296, 990))
        self.hubHolder.setObjectName("hubHolder")
        self.rightSidebarHolder = QtWidgets.QWidget(self.centralwidget)
        self.rightSidebarHolder.setGeometry(QtCore.QRect(1608, 0, 312, 990))
        self.rightSidebarHolder.setObjectName("rightSidebarHolder")
        self.baseWidget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.baseWidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.baseWidget.setMenuBar(self.menubar)
        self.actionChunky = QtWidgets.QAction(self.baseWidget)
        self.actionChunky.setObjectName("actionChunky")
        self.actionSave = QtWidgets.QAction(self.baseWidget)
        self.actionSave.setObjectName("actionSave")
        self.actionBalls = QtWidgets.QAction(self.baseWidget)
        self.actionBalls.setObjectName("actionBalls")
        self.actionBo = QtWidgets.QAction(self.baseWidget)
        self.actionBo.setObjectName("actionBo")
        self.actionMilligan = QtWidgets.QAction(self.baseWidget)
        self.actionMilligan.setObjectName("actionMilligan")
        self.actionCranjis = QtWidgets.QAction(self.baseWidget)
        self.actionCranjis.setObjectName("actionCranjis")
        self.menuFile.addAction(self.actionChunky)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionBalls)
        self.menuEdit.addAction(self.actionBo)
        self.menuEdit.addAction(self.actionMilligan)
        self.menuView.addAction(self.actionCranjis)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.baseWidget)
        self.baseWidget.showMaximized()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.baseWidget.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionChunky.setText(_translate("MainWindow", "Chunky"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionBalls.setText(_translate("MainWindow", "Balls"))
        self.actionBo.setText(_translate("MainWindow", "Bo"))
        self.actionMilligan.setText(_translate("MainWindow", "Milligan"))
        self.actionCranjis.setText(_translate("MainWindow", "Cranjis"))


app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow(MainWindow)
ui.setupUi()
MainWindow.show()
sys.exit(app.exec_())


'''
d = DataStorage.DataStorage()
defaultPlayer = d.playersDB_GetPlayer(266)


app = QtWidgets.QApplication(sys.argv)
playerResultWidget = QtWidgets.QWidget()
ui = Ui_playerResultWidget(playerResultWidget)
ui.setupUi()
ui.updatePlayer(defaultPlayer)
playerResultWidget.show()
'''

#sys.exit(app.exec_())

