# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1012)
        self.leftSidebarWidget = QtWidgets.QWidget(Form)
        self.leftSidebarWidget.setGeometry(QtCore.QRect(0, 0, 312, 1012))
        self.leftSidebarWidget.setObjectName("leftSidebarWidget")
        self.rightSidebarWidget = QtWidgets.QWidget(Form)
        self.rightSidebarWidget.setGeometry(QtCore.QRect(1608, 0, 312, 1012))
        self.rightSidebarWidget.setObjectName("rightSidebarWidget")
        self.mainWindowWidget = QtWidgets.QWidget(Form)
        self.mainWindowWidget.setGeometry(QtCore.QRect(312, 0, 1296, 1012))
        self.mainWindowWidget.setObjectName("mainWindowWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
