# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1012)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftSidebarHolder = QtWidgets.QWidget(self.centralwidget)
        self.leftSidebarHolder.setGeometry(QtCore.QRect(0, 0, 312, 990))
        self.leftSidebarHolder.setObjectName("leftSidebarHolder")
        self.hubHolder = QtWidgets.QWidget(self.centralwidget)
        self.hubHolder.setGeometry(QtCore.QRect(312, 0, 1296, 990))
        self.hubHolder.setObjectName("hubHolder")
        self.rightSidebarHolder = QtWidgets.QWidget(self.centralwidget)
        self.rightSidebarHolder.setGeometry(QtCore.QRect(1608, 0, 312, 990))
        self.rightSidebarHolder.setObjectName("rightSidebarHolder")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionChunky = QtWidgets.QAction(MainWindow)
        self.actionChunky.setObjectName("actionChunky")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionBalls = QtWidgets.QAction(MainWindow)
        self.actionBalls.setObjectName("actionBalls")
        self.actionBo = QtWidgets.QAction(MainWindow)
        self.actionBo.setObjectName("actionBo")
        self.actionMilligan = QtWidgets.QAction(MainWindow)
        self.actionMilligan.setObjectName("actionMilligan")
        self.actionCranjis = QtWidgets.QAction(MainWindow)
        self.actionCranjis.setObjectName("actionCranjis")
        self.menuFile.addAction(self.actionChunky)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionBalls)
        self.menuEdit.addAction(self.actionBo)
        self.menuEdit.addAction(self.actionMilligan)
        self.menuView.addAction(self.actionCranjis)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionChunky.setText(_translate("MainWindow", "Chunky"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionBalls.setText(_translate("MainWindow", "Balls"))
        self.actionBo.setText(_translate("MainWindow", "Bo"))
        self.actionMilligan.setText(_translate("MainWindow", "Milligan"))
        self.actionCranjis.setText(_translate("MainWindow", "Cranjis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

703-244-8723
