# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otherAttributesWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_otherAttributesWidget(object):
    def setupUi(self, otherAttributesWidget):
        otherAttributesWidget.setObjectName("otherAttributesWidget")
        otherAttributesWidget.resize(271, 108)
        self.otherLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.otherLabel.setGeometry(QtCore.QRect(5, 0, 47, 13))
        self.otherLabel.setObjectName("otherLabel")
        self.heightLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.heightLabel.setGeometry(QtCore.QRect(10, 20, 55, 13))
        self.heightLabel.setObjectName("heightLabel")
        self.verticalLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.verticalLabel.setGeometry(QtCore.QRect(10, 40, 55, 13))
        self.verticalLabel.setObjectName("verticalLabel")
        self.shotInsideLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.shotInsideLabel.setGeometry(QtCore.QRect(10, 60, 55, 13))
        self.shotInsideLabel.setObjectName("shotInsideLabel")
        self.dunkLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.dunkLabel.setGeometry(QtCore.QRect(10, 80, 55, 13))
        self.dunkLabel.setObjectName("dunkLabel")
        self.dunkAttributeLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.dunkAttributeLabel.setGeometry(QtCore.QRect(70, 80, 20, 13))
        self.dunkAttributeLabel.setObjectName("dunkAttributeLabel")
        self.shotInsideAttributeLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.shotInsideAttributeLabel.setGeometry(QtCore.QRect(70, 60, 20, 13))
        self.shotInsideAttributeLabel.setObjectName("shotInsideAttributeLabel")
        self.verticalAttributeLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.verticalAttributeLabel.setGeometry(QtCore.QRect(70, 40, 20, 13))
        self.verticalAttributeLabel.setObjectName("verticalAttributeLabel")
        self.heightAttributeLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.heightAttributeLabel.setGeometry(QtCore.QRect(70, 20, 20, 13))
        self.heightAttributeLabel.setObjectName("heightAttributeLabel")
        self.line_2 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 36, 80, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 56, 80, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 76, 80, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_5.setGeometry(QtCore.QRect(10, 100, 250, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.standingDunkLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.standingDunkLabel.setGeometry(QtCore.QRect(100, 20, 55, 13))
        self.standingDunkLabel.setObjectName("standingDunkLabel")
        self.standingDunkAttributeLabel = QtWidgets.QLabel(otherAttributesWidget)
        self.standingDunkAttributeLabel.setGeometry(QtCore.QRect(160, 20, 20, 13))
        self.standingDunkAttributeLabel.setObjectName("standingDunkAttributeLabel")
        self.line_7 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_7.setGeometry(QtCore.QRect(100, 36, 80, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_10 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_10.setGeometry(QtCore.QRect(85, 15, 20, 81))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(otherAttributesWidget)
        self.line_11.setGeometry(QtCore.QRect(175, 15, 20, 81))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line = QtWidgets.QFrame(otherAttributesWidget)
        self.line.setGeometry(QtCore.QRect(38, 0, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(otherAttributesWidget)
        QtCore.QMetaObject.connectSlotsByName(otherAttributesWidget)

    def retranslateUi(self, otherAttributesWidget):
        _translate = QtCore.QCoreApplication.translate
        otherAttributesWidget.setWindowTitle(_translate("otherAttributesWidget", "otherAttributesWidget"))
        self.otherLabel.setText(_translate("otherAttributesWidget", "Other"))
        self.heightLabel.setText(_translate("otherAttributesWidget", "Height"))
        self.verticalLabel.setText(_translate("otherAttributesWidget", "Vertical"))
        self.shotInsideLabel.setText(_translate("otherAttributesWidget", "Shot Ins"))
        self.dunkLabel.setText(_translate("otherAttributesWidget", "Dunk"))
        self.dunkAttributeLabel.setText(_translate("otherAttributesWidget", "99"))
        self.shotInsideAttributeLabel.setText(_translate("otherAttributesWidget", "99"))
        self.verticalAttributeLabel.setText(_translate("otherAttributesWidget", "99"))
        self.heightAttributeLabel.setText(_translate("otherAttributesWidget", "7\'1\""))
        self.standingDunkLabel.setText(_translate("otherAttributesWidget", "Stand Dunk"))
        self.standingDunkAttributeLabel.setText(_translate("otherAttributesWidget", "99"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    otherAttributesWidget = QtWidgets.QWidget()
    ui = Ui_otherAttributesWidget()
    ui.setupUi(otherAttributesWidget)
    otherAttributesWidget.show()
    sys.exit(app.exec_())
