# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerSearchLeftSidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(312, 1012)
        self.searchBarWidget = QtWidgets.QWidget(Form)
        self.searchBarWidget.setGeometry(QtCore.QRect(0, 0, 312, 200))
        self.searchBarWidget.setObjectName("searchBarWidget")
        self.playerLookupWidget = QtWidgets.QWidget(Form)
        self.playerLookupWidget.setGeometry(QtCore.QRect(0, 200, 312, 812))
        self.playerLookupWidget.setObjectName("playerLookupWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
