# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchWidget(object):
    def setupUi(self, searchWidget):
        searchWidget.setObjectName("searchWidget")
        searchWidget.resize(313, 199)
        self.searchEntry = QtWidgets.QLineEdit(searchWidget)
        self.searchEntry.setGeometry(QtCore.QRect(50, 10, 171, 21))
        self.searchEntry.setText("")
        self.searchEntry.setObjectName("searchEntry")
        self.searchType = QtWidgets.QComboBox(searchWidget)
        self.searchType.setGeometry(QtCore.QRect(230, 10, 71, 21))
        self.searchType.setObjectName("searchType")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchLabel = QtWidgets.QLabel(searchWidget)
        self.searchLabel.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.searchLabel.setObjectName("searchLabel")
        self.resultList = QtWidgets.QListView(searchWidget)
        self.resultList.setGeometry(QtCore.QRect(10, 40, 211, 151))
        self.resultList.setObjectName("resultList")
        self.resultListScroll = QtWidgets.QScrollBar(searchWidget)
        self.resultListScroll.setGeometry(QtCore.QRect(220, 40, 20, 151))
        self.resultListScroll.setOrientation(QtCore.Qt.Vertical)
        self.resultListScroll.setObjectName("resultListScroll")
        self.searchPlayerButton = QtWidgets.QCommandLinkButton(searchWidget)
        self.searchPlayerButton.setGeometry(QtCore.QRect(240, 140, 61, 41))
        self.searchPlayerButton.setObjectName("searchPlayerButton")

        self.retranslateUi(searchWidget)
        QtCore.QMetaObject.connectSlotsByName(searchWidget)

    def retranslateUi(self, searchWidget):
        _translate = QtCore.QCoreApplication.translate
        searchWidget.setWindowTitle(_translate("searchWidget", "searchWidget"))
        self.searchType.setItemText(0, _translate("searchWidget", "Player"))
        self.searchType.setItemText(1, _translate("searchWidget", "Gauntlet"))
        self.searchType.setItemText(2, _translate("searchWidget", "Team"))
        self.searchType.setItemText(3, _translate("searchWidget", "Faction"))
        self.searchType.setItemText(4, _translate("searchWidget", "CEO"))
        self.searchType.setItemText(5, _translate("searchWidget", "New"))
        self.searchLabel.setText(_translate("searchWidget", "Search:"))
        self.searchPlayerButton.setText(_translate("searchWidget", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchWidget = QtWidgets.QWidget()
    ui = Ui_searchWidget()
    ui.setupUi(searchWidget)
    searchWidget.show()
    sys.exit(app.exec_())
